# DEEP SCANNER V3.0 CONFIGURATION

general:
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36"
  timeout: 5
  retries: 3
  threads: 100

scanning:
  ports: [21, 22, 23, 25, 53, 80, 110, 139, 143, 443, 445, 3306, 3389, 8080, 8443]
  subdomain_wordlist: "wordlists/subdomains.txt"
  param_wordlist: "wordlists/params.txt"
  payloads:
    xss: "wordlists/payloads/xss.txt"
    sqli: "wordlists/payloads/sqli.txt"

exploit_simulation:
  enabled: true
  risk_level: high
  ai_model_path: "ai/fuzz_model.h5"
  ai_training:
    max_tokens: 10000
    sequence_length: 50
    embedding_dim: 128
    lstm_units: [64, 32]
    dropout_rate: 0.3

malware_detection:
  scan_depth: 5
  alert_threshold: 0.8
  known_malware_paths: [
    "/.hidden/malware",
    "/uploads/shell.php",
    "/wp-content/uploads/backdoor.php"
  ]

zero_day_checker:
  cve_database: "wordlists/cve_db.json"

output:
  results_dir: "results"
  logs_dir: "logs"
